"""empty message

Revision ID: abfecea582ea
Revises: 705c0c7ba943
Create Date: 2023-08-12 00:58:17.884462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abfecea582ea'
down_revision = '705c0c7ba943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('album',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('lyrics',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=4096),
               existing_nullable=True)
        batch_op.alter_column('s3_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('thumbnail_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('s3_key',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('lyrics',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('album',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
